create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  data jsonb default '{}'::jsonb,
  is_published boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.notification_devices (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null,
  push_token text not null,
  updated_at timestamptz not null default now(),
  unique(user_id, platform, push_token)
);

alter table public.notifications enable row level security;
alter table public.notification_devices enable row level security;

drop policy if exists "Authenticated users can read published notifications" on public.notifications;
create policy "Authenticated users can read published notifications" on public.notifications
for select to authenticated using (is_published = true);

drop policy if exists "Users can register own notification device" on public.notification_devices;
create policy "Users can register own notification device" on public.notification_devices
for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can update own notification device" on public.notification_devices;
create policy "Users can update own notification device" on public.notification_devices
for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

alter table public.notifications replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null;
end $$;
